samples:
  #westra_eqtl_hg19:
  #mc_cardio:
  #mp_cardio:
  #cardiogenics_mc_mp_meta:
  #fairfax.mateQTL:
  #test.meta.cardio.fairfax:
  #Brain-eMeta:
  #Brain_m_Meta_rm_NA:
  #dev_brain_eQTLs:
  #cis_meta_mono_card_fairfax_mesa:
  #cis_eQTLsFDR0_05_ProbeLevel_blood_31k:
  #B_CELL_NAIVE:
  #eqtl_fetal_brain_brien_et_al_query_format_hg19:
  #FB_Brain_mQTL_rsid:
  meta_Psyc_COGA_ROSMAP:
  #STARNET_MP.chrall.CPRA_b37:
  #CARDIOGENICS_MC:
  #CARDIOGENICS_MP:
  #CD14_47231_414_b:
  #IFN_47231_367_b:
  #LPS24_47231_322_b:
  #LPS2_47231_261_b:
  #MESA_AFA_MC:
  #MESA_HIS_MC:
  #MESA_CAU_MC:
  #STARNET_MP:
  #STARNET_FC:
GWAS:
  #MVP_AUD_2019:
  #MVP_AUDIT-C_2019:
  #PGC2018:
  #SCZAUD_2019:
  #Liu2019drnkwk.chrall.CPRA_b37.rsid:
  #audit_c_SanchezRoige2018:
  #audit_p_SanchezRoige2018:
  #audit_t_SanchezRoige2018: 
  #METAANALYSIS_MVP_AUD_PGC_COGA1.tbl:
  #Liu2019drnkwk.chrall.CPRA_b37:
  AUDSCZ_ASSET_forManav_convergent_June2020:
  #SCZAUD_2019:
  #METAANALYSIS_MVP_AUD_PGC_COGA1.rsids:
chromo:
  1:
  2:
  3:
  4:
  5:
  6:
  7:
  8:
  9:
  10:
  11:
  12:
  13:
  14:
  15:
  16:
  17:
  18:
  19:
  20:
  21:
  22: